name: CICD testing with CITS
on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

env:
  ENVIRONEMENT_TO_EXECUTE: TEST
  REMOTE_GRID_URL: ${{ secrets.REMOTE_EXECUTION_URL }}
jobs:
  build:
   
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
     - name: Setup Java 21
       uses: actions/setup-java@v4
       with:
         distribution: 'temurin'
         java-version: '21' 
     - name: Setup permissions
       run: chmod -R 755 ./
     - name: Run CITS Test
       run: Run.command -run -project_location "/Projects/MyFirstProject" -release "BAT" -testset "SET1" -setEnv "run.ExecutionMode=Grid" -setEnv "run.RemoteGridURL=$REMOTE_GRID_URL" -setEnv "run.TestEnv=$ENVIRONEMENT_TO_EXECUTE"
     - name: Upload Results
       uses: actions/upload-artifact@v4
       with:
        name: my-artifact
        path: Projects/MyFirstProject/Results/TestExecution/BAT/SET1/Latest    
